### ISSUE TITLE
versionCode was not increased

### ISSUE THREAD

**Issue by IzzySoft** [Alcatraz323/audiohq_md2#5]
Nice to see there was another release (I didn't check for a while)! But it seems stable 8 shares its `versionCode` (29) with the previous release aka stable 7. Can you please make sure to always increase the `versionCode` when releasing?  Makes it easier to detect updates :wink: Thanks!

**Comment by Alcatraz323** [comment]
done and updated for 12L

**Comment by IzzySoft** [comment]
Thanks!

**Comment by IzzySoft** [comment]
Looks like you forgot it again :scream: Maybe set a reminder? Is there something like a "pre-tag" hook? :thinking:
